spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/water_detection_data
    username: root
    password: 20041119LYS&lys

server:

cors:
  allowed-origins: http://localhost:5173

